import {
  FileText,
  CheckCircle,
  Clock,
  DollarSign,
  Smartphone,
  Users,
  Package,
  Shield,
  TrendingUp,
  Download,
  Search,
  ShoppingCart,
  MapPin,
  CreditCard,
  Bell,
  BarChart3,
  Camera,
  Wallet,
  Star,
  Calendar,
  Phone,
  MessageSquare,
  Truck,
  ClipboardList,
  Building2,
  Activity,
  AlertCircle,
  Lock,
  Database,
  Zap,
  Globe,
  FileBarChart,
} from "lucide-react";

export const packages = {
  mvp: {
    name: "MVP Package",
    price: "₦12,000,000",
    timeline: "5-6 months",
    description: "Essential features to launch and test market fit",
    bestFor: "Testing market fit with essential features",
  },
  standard: {
    name: "Standard Package",
    price: "₦18,000,000",
    timeline: "5-6 months",
    description: "Full-featured platform with competitive advantages",
    bestFor: "Serious market entry with competitive features",
  },
  enterprise: {
    name: "Enterprise Package",
    price: "₦28,000,000",
    timeline: "5-6 months",
    description: "Advanced AI, compliance, and scale-ready infrastructure",
    bestFor: "Nationwide scale with investor backing",
  },
};

export const subscriptionPlans = {
  mvp: {
    name: "MVP Subscription",
    price: "₦5,000,000",
    duration: "3 months",
    description: "Essential pharmacy management features",
    bestFor: "Small to medium pharmacies starting digitization",
    features: "mvp",
  },
  standard: {
    name: "Standard Subscription",
    price: "₦7,000,000",
    duration: "6 months",
    description: "Advanced features with analytics and integrations",
    bestFor: "Growing pharmacies with multiple locations",
    features: "standard",
  },
  enterprise: {
    name: "Enterprise Subscription",
    price: "₦10,000,000",
    duration: "12 months",
    description: "Full enterprise features with AI and compliance",
    bestFor: "Large pharmacy chains and enterprise clients",
    features: "enterprise",
  },
};

export const appFeatures = {
  user: {
    title: "User App (Patient/Customer)",
    icon: <Smartphone className="w-6 h-6" />,
    color: "blue",
    sections: [
      {
        title: "Smart Search & Discovery",
        icon: <Search className="w-5 h-5" />,
        features: [
          {
            name: "Intelligent Drug Search",
            desc: "Search by drug name, brand, ailment, or symptoms",
            included: true,
          },
          {
            name: "Auto-suggest & Autocomplete",
            desc: "Real-time suggestions as you type",
            included: true,
          },
          {
            name: "Advanced Filters",
            desc: "Filter by price, distance, delivery speed, ratings, prescription required",
            included: true,
          },
          {
            name: "AI Drug Recommendations",
            desc: "Suggests alternatives and generics when brand unavailable",
            included: true,
          },
          {
            name: "Voice Search",
            desc: "Search medications using voice commands",
            included: true,
          },
        ],
      },
      {
        title: "Prescription Management",
        icon: <Camera className="w-5 h-5" />,
        features: [
          {
            name: "Prescription Upload",
            desc: "Upload via camera, gallery, or PDF",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "OCR Technology",
            desc: "Automatic prescription text recognition and drug detection",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Prescription History",
            desc: "Store and manage all past prescriptions securely",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Doctor Prescription Sharing",
            desc: "Share prescriptions directly from doctors/hospitals",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Smart Validation",
            desc: "AI checks for dosage conflicts and drug interactions",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Shopping Experience",
        icon: <ShoppingCart className="w-5 h-5" />,
        features: [
          {
            name: "Add to Cart / Buy Now",
            desc: "Simple checkout flow with instant purchase option",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multi-Pharmacy Cart",
            desc: "Order from multiple pharmacies in one transaction",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Quick Reorder",
            desc: "One-click reorder from order history",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Scheduled Orders",
            desc: "Schedule delivery for specific dates/times",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Recurring Subscriptions",
            desc: "Auto-refill for chronic medications on schedule",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Wishlist & Save for Later",
            desc: "Save drugs for future purchase",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Payment & Wallet",
        icon: <CreditCard className="w-5 h-5" />,
        features: [
          {
            name: "Paystack Integration",
            desc: "Card payments, bank transfer, USSD",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Flutterwave Integration",
            desc: "Alternative payment gateway for redundancy",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Save Card for Future",
            desc: "Tokenized card storage for quick checkout",
            mvp: true,
            standard: true,
            enterprise: true,
          },

          {
            name: "QuickMed Wallet",
            desc: "In-app wallet with auto-refill option",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Split Payments",
            desc: "Combine wallet + card + promo codes",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Promo Codes & Coupons",
            desc: "Apply discount codes at checkout",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Loyalty Points System",
            desc: "Earn points on purchases, redeem for discounts",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Order Tracking & Delivery",
        icon: <MapPin className="w-5 h-5" />,
        features: [
          {
            name: "Real-time Order Tracking",
            desc: "Live map showing rider location and ETA",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Status Updates",
            desc: "Confirmed → Processing → Out for Delivery → Delivered",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Push Notifications",
            desc: "Real-time alerts for order updates",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "SMS Notifications",
            desc: "Backup notifications via text message",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery ETA",
            desc: "Accurate estimated time of arrival",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Contact Rider/Pharmacy",
            desc: "In-app call or chat with rider or pharmacy",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Instructions",
            desc: "Add specific delivery notes (gate code, landmark)",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "User Profile & Management",
        icon: <Users className="w-5 h-5" />,
        features: [
          {
            name: "Profile Management",
            desc: "Edit personal info, contact details, preferences",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multiple Addresses",
            desc: "Save home, office, and multiple delivery addresses",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order History",
            desc: "Complete purchase history with filters and search",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Digital Receipts",
            desc: "In-app and downloadable PDF receipts",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Family Accounts",
            desc: "Manage prescriptions for dependents or elderly",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Health Profile",
            desc: "Store allergies, chronic conditions, blood type",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Spending Analytics",
            desc: "Track healthcare spending by month/category",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Discovery & Engagement",
        icon: <Star className="w-5 h-5" />,
        features: [
          {
            name: "Nearby Pharmacies Map",
            desc: "View pharmacies on interactive map with details",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Pharmacy Ratings & Reviews",
            desc: "See ratings, read reviews, check opening hours",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Smart Recommendations",
            desc: "Suggest supplements based on order history",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Refill Reminders",
            desc: "Notifications when chronic medication is due",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Health Tips & Articles",
            desc: "Curated health content and wellness tips",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Seasonal Campaigns",
            desc: "Special offers for flu season, allergy season, etc.",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Support & Help",
        icon: <MessageSquare className="w-5 h-5" />,
        features: [
          {
            name: "FAQs & Help Center",
            desc: "Comprehensive self-service help articles",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "In-app Chat Support",
            desc: "Live chat with customer support team",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Phone Support",
            desc: "Direct call to support center",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Email Ticketing",
            desc: "Submit and track support tickets",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Disputes & Refunds",
            desc: "Request refunds or report issues",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Additional Features",
        icon: <Zap className="w-5 h-5" />,
        features: [
          {
            name: "Dark Mode",
            desc: "Eye-friendly dark theme option",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multi-language Support",
            desc: "English, Yoruba, Hausa, Igbo",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Offline Mode",
            desc: "View order history and saved items offline",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Accessibility Features",
            desc: "Screen reader support, larger text options",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
    ],
  },
  pharmacy: {
    title: "Pharmacy App (Partner Portal)",
    icon: <Building2 className="w-6 h-6" />,
    color: "green",
    sections: [
      {
        title: "Registration & Onboarding",
        icon: <ClipboardList className="w-5 h-5" />,
        features: [
          {
            name: "Pharmacy Registration",
            desc: "Submit license, CAC, NAFDAC documents for verification",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Admin Verification",
            desc: "Admin approval process before going live",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Subscription Management",
            desc: "Choose and manage subscription tiers",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multi-branch Support",
            desc: "Manage multiple pharmacy locations under one account",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Staff Account Management",
            desc: "Create accounts for pharmacists and staff with role permissions",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Inventory Management",
        icon: <Package className="w-5 h-5" />,
        features: [
          {
            name: "Add/Edit/Delete Drugs",
            desc: "Full CRUD operations for drug catalog",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Stock Level Tracking",
            desc: "Real-time inventory quantity management",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Low Stock Alerts",
            desc: "Automatic notifications when stock runs low",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Expiry Date Management",
            desc: "Track expiry dates, auto-alert for near-expiry drugs",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Bulk Upload",
            desc: "Import inventory via Excel/CSV",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Barcode/QR Scanning",
            desc: "Scan products to update stock quickly",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "AI Reorder Suggestions",
            desc: "Smart recommendations for restocking based on sales patterns",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Stock Forecasting",
            desc: "Predict future stock needs using AI analytics",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Batch/Lot Tracking",
            desc: "Track specific batches for recall management",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Order Management",
        icon: <ShoppingCart className="w-5 h-5" />,
        features: [
          {
            name: "Accept/Decline Orders",
            desc: "Review and approve incoming orders",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Status Updates",
            desc: "Update progress: Processing → Ready → Out for Delivery",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Notifications",
            desc: "Real-time alerts for new orders",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Search & Filter",
            desc: "Find orders by date, customer, drug, status",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Prescription Verification",
            desc: "View uploaded prescriptions, verify authenticity",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Customer Communication",
            desc: "Chat with customers about orders",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Print Invoices",
            desc: "Generate and print order invoices",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Electronic Invoice Generation",
            desc: "Generate electronic invoices for customer drug purchases",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Bulk Order Processing",
            desc: "Process multiple orders simultaneously",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Rider & Delivery Management",
        icon: <Truck className="w-5 h-5" />,
        features: [
          {
            name: "Manual Rider Assignment",
            desc: "Assign specific rider to order",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Auto-assignment System",
            desc: "System automatically assigns nearest available rider",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Track Active Deliveries",
            desc: "Real-time map of riders delivering your orders",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Zones",
            desc: "Set service areas and delivery boundaries",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Scheduling",
            desc: "Manage delivery time slots and capacity",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Rider Communication",
            desc: "Chat with assigned riders",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Performance",
            desc: "View on-time delivery rates and rider ratings",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Financial & Analytics",
        icon: <BarChart3 className="w-5 h-5" />,
        features: [
          {
            name: "Sales Dashboard",
            desc: "Daily, weekly, monthly revenue overview",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Transaction History",
            desc: "Complete payment and order records",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Top-selling Drugs",
            desc: "Analytics on most popular medications",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Customer Insights",
            desc: "Repeat customer rates, order frequency",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Revenue Forecasting",
            desc: "AI-powered sales predictions",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Location Heatmaps",
            desc: "See order concentration by area",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Exportable Reports",
            desc: "Download analytics as PDF/Excel",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Commission Tracking",
            desc: "View platform fees and net earnings",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Profit Margin Analysis",
            desc: "Track profitability by drug category",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Compliance & Documentation",
        icon: <FileText className="w-5 h-5" />,
        features: [
          {
            name: "License Management",
            desc: "Upload and track pharmacy licenses",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "NAFDAC Certificate",
            desc: "Submit and renew NAFDAC approvals",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Expiry Alerts",
            desc: "Notifications for expiring certifications",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Regulatory Access",
            desc: "Grant read-only access to regulators",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Audit Trails",
            desc: "Complete transaction logs for compliance",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Document Storage",
            desc: "Secure cloud storage for all documents",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Marketing & Promotions",
        icon: <TrendingUp className="w-5 h-5" />,
        features: [
          {
            name: "Create Promo Codes",
            desc: "Generate discount codes for customers",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Featured Listings",
            desc: "Pay to appear in top search results",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Flash Sales",
            desc: "Run time-limited special offers",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Customer Notifications",
            desc: "Send push notifications to nearby customers",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Loyalty Programs",
            desc: "Create pharmacy-specific reward programs",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Settings & Configuration",
        icon: <Shield className="w-5 h-5" />,
        features: [
          {
            name: "Operating Hours",
            desc: "Set opening/closing times, holidays",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Service Areas",
            desc: "Define delivery coverage zones",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Charges",
            desc: "Set custom delivery fees by distance/zone",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Minimum Order Value",
            desc: "Set minimum purchase requirements",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Auto-accept Settings",
            desc: "Automatically accept orders during peak hours",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Notification Preferences",
            desc: "Customize alert settings",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
    ],
  },
  rider: {
    title: "Rider App (Delivery Partner)",
    icon: <Truck className="w-6 h-6" />,
    color: "orange",
    sections: [
      {
        title: "Authentication & Onboarding",
        icon: <Lock className="w-5 h-5" />,
        features: [
          {
            name: "Rider Registration",
            desc: "Submit documents for approval (ID, license, vehicle)",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Admin Verification",
            desc: "Background check and approval process",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Training Resources",
            desc: "Access safety guides and delivery protocols",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Profile Management",
            desc: "Update vehicle info, contact details, availability",
            mvp: true,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Order & Delivery Management",
        icon: <ClipboardList className="w-5 h-5" />,
        features: [
          {
            name: "Accept/Reject Orders",
            desc: "View and choose delivery assignments",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Details",
            desc: "View pickup location, delivery address, customer contact",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Status Updates",
            desc: "Update: Picked Up → On the Way → Delivered",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multiple Deliveries",
            desc: "Accept and manage multiple orders simultaneously",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Smart Batching",
            desc: "System groups nearby deliveries for efficiency",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Order History",
            desc: "View all past completed deliveries",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Instructions",
            desc: "View customer notes and special instructions",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Navigation & Routing",
        icon: <MapPin className="w-5 h-5" />,
        features: [
          {
            name: "Integrated Maps",
            desc: "Google Maps or Mapbox navigation",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Turn-by-turn Navigation",
            desc: "Real-time GPS directions",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Route Optimization",
            desc: "Best route for multiple deliveries",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Live Traffic Updates",
            desc: "Avoid congestion with real-time traffic data",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Offline Maps",
            desc: "Navigate even without internet connection",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "ETA Updates",
            desc: "Real-time arrival time shown to customer",
            mvp: true,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Proof of Delivery",
        icon: <Camera className="w-5 h-5" />,
        features: [
          {
            name: "OTP Verification",
            desc: "Customer enters code to confirm receipt",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Digital Signature",
            desc: "Capture customer signature on delivery",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Photo Proof",
            desc: "Take photo of delivered package",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Geo-tagged Proof",
            desc: "GPS coordinates saved for each delivery",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Delivery Notes",
            desc: "Add comments about delivery (e.g., left with neighbor)",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Earnings & Payments",
        icon: <DollarSign className="w-5 h-5" />,
        features: [
          {
            name: "Earnings Dashboard",
            desc: "View daily, weekly, monthly income",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Per-delivery Breakdown",
            desc: "See payment for each completed delivery",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Payout Requests",
            desc: "Request withdrawal of earned money",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Payout Schedule",
            desc: "View next automatic payout date",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Mileage Tracking",
            desc: "Track distance traveled for each delivery",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Incentive Programs",
            desc: "View bonuses for peak hours, high performance",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Fuel Allowance",
            desc: "In-app wallet for fuel reimbursements",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Tax Documents",
            desc: "Download earnings statements for tax filing",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Communication",
        icon: <Phone className="w-5 h-5" />,
        features: [
          {
            name: "Call Customer",
            desc: "Direct in-app call to customer",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Call Pharmacy",
            desc: "Contact pharmacy for pickup issues",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "In-app Chat",
            desc: "Text chat with customer or pharmacy",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Masked Phone Numbers",
            desc: "Privacy-protected calls (numbers hidden)",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Quick Messages",
            desc: "Pre-written templates (I've arrived, Running late, etc.)",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Performance & Safety",
        icon: <Activity className="w-5 h-5" />,
        features: [
          {
            name: "Online/Offline Toggle",
            desc: "Control availability for new deliveries",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Performance Rating",
            desc: "View your rating from customers and pharmacies",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Stats",
            desc: "Total deliveries, on-time rate, customer satisfaction",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Panic Button",
            desc: "Emergency alert to QuickMed central dispatch",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Safety Tips",
            desc: "Best practices for safe deliveries",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Incident Reporting",
            desc: "Report accidents, theft, or issues",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Notifications & Alerts",
        icon: <Bell className="w-5 h-5" />,
        features: [
          {
            name: "New Order Alerts",
            desc: "Push notification for available deliveries",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Payment Confirmations",
            desc: "Notification when earnings are deposited",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Route Updates",
            desc: "Alerts for traffic or route changes",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Promotional Alerts",
            desc: "Info about incentive programs or bonuses",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
    ],
  },
  admin: {
    title: "Admin Dashboard (Web Portal)",
    icon: <Shield className="w-6 h-6" />,
    color: "purple",
    sections: [
      {
        title: "Central Control Dashboard",
        icon: <BarChart3 className="w-5 h-5" />,
        features: [
          {
            name: "System Overview",
            desc: "Real-time stats: users, pharmacies, riders, orders, revenue",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Live Order Map",
            desc: "Global map showing all active deliveries across Nigeria",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Key Metrics Dashboard",
            desc: "Daily active users, order volume, growth trends",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Performance Alerts",
            desc: "Notifications for system issues or anomalies",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Custom Dashboards",
            desc: "Create personalized views for different admin roles",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "User Management",
        icon: <Users className="w-5 h-5" />,
        features: [
          {
            name: "View All Users",
            desc: "Complete customer database with search/filter",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "User Details",
            desc: "View profile, order history, spending, activity",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Suspend/Ban Users",
            desc: "Disable accounts for policy violations",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "User Support",
            desc: "View support tickets, resolve issues",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Activity Logs",
            desc: "Track user actions for security/compliance",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Bulk User Actions",
            desc: "Mass updates or notifications to user segments",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "User Segmentation",
            desc: "Group users by behavior, location, spending",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Pharmacy Management",
        icon: <Building2 className="w-5 h-5" />,
        features: [
          {
            name: "Pharmacy Approval",
            desc: "Review and approve new pharmacy applications",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "License Verification",
            desc: "Check NAFDAC certificates, pharmacy licenses",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Pharmacy Database",
            desc: "Complete list with search, filter by location/status",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Subscription Management",
            desc: "View and manage pharmacy subscription plans",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Inventory Monitoring",
            desc: "View pharmacy stock levels, expired drugs",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Compliance Tracking",
            desc: "Monitor expiring licenses and certifications",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Performance Scores",
            desc: "Rate pharmacies by delivery time, customer satisfaction",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Suspend/Remove Pharmacy",
            desc: "Disable pharmacies for violations",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multi-branch Management",
            desc: "View and manage pharmacy chains",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Rider Management",
        icon: <Truck className="w-5 h-5" />,
        features: [
          {
            name: "Rider Approval",
            desc: "Review and approve rider applications",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Rider Database",
            desc: "Complete list with search, filter, status",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Live Rider Tracking",
            desc: "Real-time map of all active riders",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Performance Monitoring",
            desc: "View delivery times, ratings, completion rates",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Earnings Management",
            desc: "Process payouts, view rider earnings",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Suspend/Remove Rider",
            desc: "Disable riders for policy violations",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Rider Incentives",
            desc: "Create and manage bonus programs",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Zone Assignment",
            desc: "Assign riders to specific delivery zones",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Order Management & Oversight",
        icon: <ShoppingCart className="w-5 h-5" />,
        features: [
          {
            name: "All Orders Dashboard",
            desc: "View active, completed, cancelled orders",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Search & Filter",
            desc: "Find orders by date, customer, pharmacy, status",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Manual Interventions",
            desc: "Reassign riders, cancel orders, issue refunds",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Live Order Tracking",
            desc: "Monitor any order in real-time on map",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Dispute Management",
            desc: "Handle customer complaints and conflicts",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Order Analytics",
            desc: "Average order value, completion rates, peak times",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Failed Order Reports",
            desc: "Analyze cancelled/failed deliveries",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Financial Management",
        icon: <DollarSign className="w-5 h-5" />,
        features: [
          {
            name: "Revenue Dashboard",
            desc: "Track total revenue, commissions, subscriptions",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Transaction Monitoring",
            desc: "View all Paystack/Flutterwave transactions",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Commission Management",
            desc: "Set and adjust commission rates by category",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Pharmacy Billing",
            desc: "Manage subscription invoices and payments",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Rider Payouts",
            desc: "Process and track delivery partner payments",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Refund Processing",
            desc: "Approve and execute customer refunds",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Financial Reports",
            desc: "Generate P&L, revenue, expense reports",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Accounting Integration",
            desc: "Export to QuickBooks, Zoho Books",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Tax Reports",
            desc: "Generate tax documents and VAT reports",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Analytics & Business Intelligence",
        icon: <FileBarChart className="w-5 h-5" />,
        features: [
          {
            name: "Sales Analytics",
            desc: "Daily, weekly, monthly revenue trends",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "User Behavior Analytics",
            desc: "Track user engagement, retention, churn",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Geographic Heatmaps",
            desc: "Visualize order density by location",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Drug Category Analysis",
            desc: "Most ordered medications by type",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Delivery Performance",
            desc: "Average delivery times, success rates",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Predictive Analytics",
            desc: "AI forecasts for demand, growth, churn",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Custom Reports",
            desc: "Build custom queries and visualizations",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Exportable Dashboards",
            desc: "Download reports as PDF, Excel, CSV",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Real-time Data Streaming",
            desc: "Live updates for critical metrics",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Regulatory & Compliance",
        icon: <FileText className="w-5 h-5" />,
        features: [
          {
            name: "Regulatory Portal Access",
            desc: "Grant NAFDAC/government read-only access",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Compliance Dashboard",
            desc: "Monitor pharmacy licenses, drug authenticity",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Audit Trails",
            desc: "Complete logs of all system actions",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Counterfeit Drug Alerts",
            desc: "Flag suspicious pharmacies or drugs",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Regulatory Reports",
            desc: "Generate compliance reports for authorities",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "License Expiry Tracking",
            desc: "Auto-alerts for expiring certifications",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Data Privacy Controls",
            desc: "GDPR/data protection compliance tools",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Marketing & Promotions",
        icon: <TrendingUp className="w-5 h-5" />,
        features: [
          {
            name: "Create Promo Codes",
            desc: "Platform-wide discount codes and campaigns",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Push Notifications",
            desc: "Send targeted notifications to user segments",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Banner Management",
            desc: "Upload and schedule promotional banners",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Email Campaigns",
            desc: "Send bulk emails to users or pharmacies",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "SMS Campaigns",
            desc: "Bulk SMS for promotions or alerts",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Referral Programs",
            desc: "Manage user and pharmacy referral bonuses",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "A/B Testing",
            desc: "Test different promotions and measure results",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Content Management",
        icon: <FileText className="w-5 h-5" />,
        features: [
          {
            name: "FAQs Management",
            desc: "Create and edit help articles",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Terms & Policies",
            desc: "Update terms of service, privacy policy",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Health Content",
            desc: "Publish health tips and educational articles",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "App Announcements",
            desc: "Create in-app announcements and updates",
            mvp: false,
            standard: true,
            enterprise: true,
          },
        ],
      },
      {
        title: "Support & Ticketing",
        icon: <MessageSquare className="w-5 h-5" />,
        features: [
          {
            name: "Support Ticket System",
            desc: "View and respond to user/pharmacy tickets",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Live Chat Dashboard",
            desc: "Handle real-time chat conversations",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Ticket Assignment",
            desc: "Assign tickets to specific support agents",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Chat Logs Archive",
            desc: "Search historical support conversations",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Response Templates",
            desc: "Pre-written responses for common issues",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Support Analytics",
            desc: "Track response times, resolution rates",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "System Settings & Configuration",
        icon: <Shield className="w-5 h-5" />,
        features: [
          {
            name: "Platform Settings",
            desc: "Configure global app settings and parameters",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Fee Management",
            desc: "Set delivery fees, service charges, commission rates",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Payment Gateway Config",
            desc: "Manage Paystack/Flutterwave API keys",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Map API Settings",
            desc: "Configure Google Maps/Mapbox credentials",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Role-Based Access Control",
            desc: "Create admin roles with specific permissions",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Multi-admin Management",
            desc: "Add Super Admin, Finance Admin, Support roles",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "System Logs",
            desc: "View all admin actions and system events",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Backup Management",
            desc: "Schedule and monitor database backups",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "API Management",
            desc: "Manage third-party API integrations",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
      {
        title: "Security & Data Protection",
        icon: <Lock className="w-5 h-5" />,
        features: [
          {
            name: "User Authentication Logs",
            desc: "Track login attempts and security events",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Two-Factor Authentication",
            desc: "2FA for admin accounts",
            mvp: false,
            standard: true,
            enterprise: true,
          },
          {
            name: "Data Encryption",
            desc: "End-to-end encryption for sensitive data",
            mvp: true,
            standard: true,
            enterprise: true,
          },
          {
            name: "Fraud Detection",
            desc: "AI alerts for suspicious transactions",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "IP Whitelisting",
            desc: "Restrict admin access by IP address",
            mvp: false,
            standard: false,
            enterprise: true,
          },
          {
            name: "Data Export/Deletion",
            desc: "GDPR-compliant user data management",
            mvp: false,
            standard: false,
            enterprise: true,
          },
        ],
      },
    ],
  },
};

export const costBreakdown = {
  mvp: [
    { item: "User Mobile App (Android & iOS)", cost: "₦3,000,000" },
    { item: "Pharmacy App (Android & iOS)", cost: "₦3,000,000" },
    { item: "Rider App (Android & iOS)", cost: "₦2,400,000" },
    { item: "Admin Dashboard", cost: "₦1,800,000" },
    { item: "Backend Development", cost: "₦1,200,000" },
    { item: "Testing & QA", cost: "₦600,000" },
  ],
  standard: [
    { item: "User Mobile App (Android & iOS)", cost: "₦4,500,000" },
    { item: "Pharmacy App (Android & iOS)", cost: "₦4,500,000" },
    { item: "Rider App (Android & iOS)", cost: "₦3,600,000" },
    { item: "Admin Dashboard", cost: "₦2,700,000" },
    { item: "Backend Development", cost: "₦1,800,000" },
    { item: "Testing & QA", cost: "₦900,000" },
  ],
  enterprise: [
    { item: "User Mobile App (Android & iOS)", cost: "₦7,000,000" },
    { item: "Pharmacy App (Android & iOS)", cost: "₦7,000,000" },
    { item: "Rider App (Android & iOS)", cost: "₦5,600,000" },
    { item: "Admin Dashboard", cost: "₦4,200,000" },
    { item: "Backend Development", cost: "₦2,800,000" },
    { item: "Testing & QA", cost: "₦1,400,000" },
  ],
};

export const paymentStructure = {
  mvp: [
    {
      phase: "Project Kickoff",
      amount: "₦1,800,000",
      percent: "15%",
      milestone:
        "Contract signing, requirements finalization, system and architectural design",
    },
    {
      phase: "UI/UX Design Completion",
      amount: "₦1,800,000",
      percent: "15%",
      milestone:
        "All app designs approved, development setup complete, Frontend Started",
    },
    {
      phase: "Backend Development",
      amount: "₦1,800,000",
      percent: "15%",
      milestone: "API development & database setup complete",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦1,800,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features started",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦1,800,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features continued",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦1,800,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features complete",
    },
    {
      phase: "Beta Testing & Final Delivery",
      amount: "₦1,200,000",
      percent: "15%",
      milestone: "Client testing complete & feedback implemented",
    },
  ],
  standard: [
    {
      phase: "Project Kickoff",
      amount: "₦2,700,000",
      percent: "15%",
      milestone:
        "Contract signing, requirements finalization, system and architectural design",
    },
    {
      phase: "UI/UX Design Completion",
      amount: "₦2,700,000",
      percent: "15%",
      milestone:
        "All app designs approved, development setup complete, Frontend Started",
    },
    {
      phase: "Backend Development",
      amount: "₦2,700,000",
      percent: "15%",
      milestone: "API development & database setup complete",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦2,700,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features started",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦2,700,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features continued",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦2,700,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features complete",
    },
    {
      phase: "Beta Testing & Final Delivery",
      amount: "₦1,800,000",
      percent: "15%",
      milestone: "Client testing complete & feedback implemented",
    },
  ],
  enterprise: [
    {
      phase: "Project Kickoff",
      amount: "₦4,200,000",
      percent: "15%",
      milestone:
        "Contract signing, requirements finalization, system and architectural design",
    },
    {
      phase: "UI/UX Design Completion",
      amount: "₦4,200,000",
      percent: "15%",
      milestone:
        "All app designs approved, development setup complete, Frontend Started",
    },
    {
      phase: "Backend Development",
      amount: "₦4,200,000",
      percent: "15%",
      milestone: "API development & database setup complete",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦4,200,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features started",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦4,200,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features continued",
    },
    {
      phase: "Mobile Apps Development",
      amount: "₦4,200,000",
      percent: "15%",
      milestone: "User, Pharmacy & Rider apps core features complete",
    },
    {
      phase: "Beta Testing & Final Delivery",
      amount: "₦2,800,000",
      percent: "10%",
      milestone: "Client testing complete & feedback implemented",
    },
  ],
};
